model_2D: 
  - ResUNet_LSTM

WHS_datasets: #imagesets_path和labelsets必须是一一对应的
  datasets_input_path: #label和image放一起
    - "/WHS/MultiResNet-SC/datasets_input/MMWHS/ct_train"
    - "/WHS/MultiResNet-SC/datasets_input/MMWHS/ct_test"
    - "/WHS/MultiResNet-SC/datasets_input/augmented/MMWHS/ct_train"

  results_output:
    statistics: "/WHS/MultiResNet-SC/statistics"
    model_state_dict: "/WHS/MultiResNet-SC/output_temp_model_dict"
